version: "3"
services:
  mongo:
    image: mvertes/alpine-mongo
    volumes:
      - "vol:/data/db"
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "11998:8081"

volumes:
  vol:
    driver: local
  cad:
    driver: local
